nome=str(input('Digite seu nome completo: ')).strip()
print('''Analisando seu nome...
------------------------------------------''')
print('Seu nome em maiúsculas é {}.'.format(nome.upper()))
print('Seu nome em minusculas é {}.'.format(nome.lower()))
cc=len(nome)
cb=nome.count(' ')
print('Seu nome tem ao todo {} letras.'.format(cc-cb))
spl=nome.split()
print('Seu primeiro nome é {} e tem {} letras.'.format(spl[0],len(spl[0])))
